---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - ../base # Relative path to the base directory
  - backstage-secrets.yaml
  - backstage-service.yaml
  - backstage.yaml
  - postgres-service.yaml
  - postgres.yaml
