name: Backstage Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensures full history and all files

    - name: Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'

    - name: Cache Yarn Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.yarn
          ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Enable Corepack (for Yarn Berry)
      run: corepack enable

    - name: Install Dependencies
      run: yarn install --immutable
      env:
        YARN_CACHE_FOLDER: ~/.cache/yarn  # Explicit cache path

    - name: Run TypeScript Compiler
      run: yarn tsc

    - name: Build Backend
      run: yarn build:backend

    - name: Build Docker Image
      run: yarn build-image
